export const MOSTRAR_PERSONAS = 'MOSTRAR_PERSONAS';
export const MOSTRAR_PERSONA = 'MOSTRAR_PERSONA';
export const AGREGAR_PERSONA = 'AGREGAR_PERSONA';
export const OBTENER_PERSONA = 'OBTENER_PERSONA';
export const EDITAR_PERSONA = 'EDITAR_PERSONA';
export const ELIMINAR_PERSONA = 'ELIMINAR_PERSONA';
export const BUSCAR_PERSONA = 'BUSCAR_PERSONA';
